---
- name: 03 - Join Nodes and Install CNI
  hosts: k8s_cluster
  become: yes
  gather_facts: no
  vars:
    # Calico CNI manifest URL
    calico_manifest_url: https://docs.tigera.io/calico/latest/manifests/calico.yaml

  tasks:
    - name: Wait for Kubernetes cluster to be available
      ansible.builtin.command: kubectl get nodes
      register: kubectl_check
      until: kubectl_check.rc == 0
      retries: 5
      delay: 5
      delegate_to: node1
      run_once: true

    - name: Install Calico CNI
      ansible.builtin.command: >
        kubectl apply -f {{ calico_manifest_url }}
      delegate_to: node1
      run_once: true
      register: cni_install
      changed_when: cni_install.rc == 0
      when: inventory_hostname == 'node1'
      
    - name: Join remaining control plane nodes (node2, node3)
      ansible.builtin.command: "{{ hostvars['node1']['k8s_control_plane_join_command'] }}"
      when:
        - inventory_hostname != 'node1'
        - inventory_hostname in groups['k8s_control_plane']
        - hostvars['node1']['k8s_control_plane_join_command'] is defined
      register: join_result
      changed_when: join_result.rc == 0
      
    - name: Ensure all worker nodes (including masters) are joinable
      ansible.builtin.command: "{{ hostvars['node1']['k8s_worker_join_command'] }}"
      when:
        # Re-joining using the worker command is sometimes necessary for hybrid nodes
        - hostvars['node1']['k8s_worker_join_command'] is defined
      register: worker_join_result
      changed_when: worker_join_result.rc == 0
      ignore_errors: yes # Ignore if node is already joined with the same token

    - name: Wait for nodes to be Ready
      ansible.builtin.command: kubectl wait --for=condition=Ready node/{{ inventory_hostname }} --timeout=300s
      delegate_to: node1
      run_once: true
