---
- name: 04 - Deploy Rook-Ceph Operator and Cluster
  hosts: node1
  become: no
  gather_facts: no
  vars:
    # Use the deploy/examples directory for 1.14+
    rook_ceph_base_url: https://raw.githubusercontent.com/rook/rook/release-1.14/deploy/examples
    
  tasks:
    - name: Create the rook-ceph namespace
      kubernetes.core.k8s:
        name: rook-ceph
        api_version: v1
        kind: Namespace
        state: present

    # --- CRITICAL FIX: Apply CRDs first (Required for Rook 1.14+) ---
    - name: Apply Rook Custom Resource Definitions (CRDs)
      kubernetes.core.k8s:
        state: present
        src: "{{ rook_ceph_base_url }}/crds.yaml"
    # ----------------------------------------------------------------

    - name: Apply common Rook manifests (RBAC, etc.)
      kubernetes.core.k8s:
        state: present
        src: "{{ rook_ceph_base_url }}/common.yaml"

    - name: Apply Rook operator manifest
      kubernetes.core.k8s:
        state: present
        src: "{{ rook_ceph_base_url }}/operator.yaml"

    # --- Patch Operator to run on Control Plane nodes ---
    - name: Patch Rook Operator to tolerate Control Plane taints
      ansible.builtin.command: >
        kubectl -n rook-ceph patch deployment rook-ceph-operator --patch '{"spec": {"template": {"spec": {"tolerations": [{"key": "node-role.kubernetes.io/control-plane", "operator": "Exists", "effect": "NoSchedule"}, {"key": "node-role.kubernetes.io/master", "operator": "Exists", "effect": "NoSchedule"}]}}}}'
      register: patch_result
      changed_when: patch_result.rc == 0
    
    - name: Wait for Rook Operator to be available
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: rook-ceph-operator
        namespace: rook-ceph
      register: rook_operator_status
      until: 
        - rook_operator_status.resources is defined
        - rook_operator_status.resources | length > 0
        - rook_operator_status.resources[0].status.readyReplicas | default(0) >= 1
      retries: 30
      delay: 10

    # --- Wait for CRD to be established ---
    - name: Wait for CephCluster CRD to be established
      ansible.builtin.command: kubectl wait --for=condition=established crd/cephclusters.ceph.rook.io --timeout=60s
      changed_when: false
    
    - name: Create temporary file for Ceph Cluster manifest
      ansible.builtin.tempfile:
        state: file
        suffix: ceph-cluster
      register: temp_cluster_manifest
      run_once: true

    - name: Deploy Ceph Cluster CRD from Template
      ansible.builtin.template:
        src: cluster-manifest.j2
        dest: "{{ temp_cluster_manifest.path }}"
      run_once: true
      vars:
        ceph_use_all_nodes: true
        ceph_use_all_devices: false 

    - name: Apply Ceph Cluster CRD
      kubernetes.core.k8s:
        state: present
        src: "{{ temp_cluster_manifest.path }}"
    
    - name: Apply Ceph Block Pool and StorageClass
      kubernetes.core.k8s:
        state: present
        src: "{{ rook_ceph_base_url }}/csi/rbd/storageclass.yaml"

    - name: Wait for rook-ceph-block StorageClass to be ready
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: rook-ceph-block
      register: sc_check
      until: 
        - sc_check.resources is defined
        - sc_check.resources | length > 0
      retries: 15
      delay: 5
