---
- name: 06 - Deploy MetalLB and Portainer
  hosts: node1
  become: true
  tasks:
    - name: Enable strictARP in kube-proxy (Required for MetalLB)
      shell: |
        kubectl get configmap kube-proxy -n kube-system -o yaml | \
        sed -e "s/strictARP: false/strictARP: true/" | \
        kubectl apply -f - -n kube-system
      register: strict_arp_patch
      changed_when: "'configured' in strict_arp_patch.stdout"
      
    - name: Add MetalLB Helm repository
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb

    - name: Install MetalLB using Helm
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: metallb-system
        create_namespace: true
        wait: true
        values:
          speaker:
            tolerateMaster: true
            
    - name: Apply MetalLB IP Pool and Interface Config
      kubernetes.core.k8s:
        state: present
        definition:
          - apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: first-pool
              namespace: metallb-system
            spec:
              addresses:
                - 10.6.4.150-10.6.4.200
              autoAssign: true

          - apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: mixed-hardware-advertisement
              namespace: metallb-system
            spec:
              ipAddressPools:
                - first-pool
              interfaces:
                - eno1
                - eno2
                
    - name: Add Portainer Helm repository
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: https://portainer.github.io/k8s/

    - name: Install Portainer using Helm
      kubernetes.core.helm:
        name: portainer
        chart_ref: portainer/portainer
        release_namespace: portainer
        create_namespace: true
        wait: true
        values:
          service:
            type: LoadBalancer
            externalTrafficPolicy: Local
            httpPort: 80
            httpsPort: 443
            edgePort: 8000
          tls:
            force: false
            
    - name: Get Portainer Service Info
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: portainer
        namespace: portainer
      register: portainer_svc
      until: portainer_svc.resources[0].status.loadBalancer.ingress is defined
      retries: 10
      delay: 5

    - name: Display Portainer Login URL
      debug:
        msg: 
          - "========================================================"
          - "DEPLOYMENT SUCCESSFUL!"
          - "Go here immediately to set your admin password:"
          - "https://{{ portainer_svc.resources[0].status.loadBalancer.ingress[0].ip }}"
          - "========================================================"
          - "NOTE: You have 5 minutes to set the password."
          - "If you get a 'timeout' error, run: kubectl rollout restart deploy portainer -n portainer"
