---
- name: 06 - Deploy MetalLB and Portainer
  hosts: node1
  become: true
  vars:
    # Define the location of the admin config for all tasks to use
    k8s_config: /etc/kubernetes/admin.conf

  tasks:
    - name: Enable strictARP in kube-proxy (Required for MetalLB)
      shell: |
        # Explicitly set KUBECONFIG for this shell session
        export KUBECONFIG={{ k8s_config }}
        kubectl get configmap kube-proxy -n kube-system -o yaml | \
        sed -e "s/strictARP: false/strictARP: true/" | \
        kubectl apply -f - -n kube-system
      register: strict_arp_patch
      changed_when: "'configured' in strict_arp_patch.stdout"
      
    - name: Add MetalLB Helm repository
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb

    - name: Install MetalLB using Helm
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: metallb-system
        create_namespace: true
        wait: true
        timeout: "10m0s"
        kubeconfig: "{{ k8s_config }}"
        values:
          # Allow the Controller (the brain) to run on Master nodes
          controller:
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Exists"
                effect: "NoSchedule"
              - key: "node-role.kubernetes.io/master"
                operator: "Exists"
                effect: "NoSchedule"
          # Allow the Speakers (the announcers) to run on Master nodes
          speaker:
            tolerateMaster: true
            
    - name: Apply MetalLB IP Pool and Interface Config
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_config }}"
        definition:
          - apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: first-pool
              namespace: metallb-system
            spec:
              addresses:
                - 10.6.4.150-10.6.4.200
              autoAssign: true

          - apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: mixed-hardware-advertisement
              namespace: metallb-system
            spec:
              ipAddressPools:
                - first-pool
              interfaces:
                - eno1
                - eno2
                
    - name: Add Portainer Helm repository
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: https://portainer.github.io/k8s/

    - name: Install Portainer using Helm
      kubernetes.core.helm:
        name: portainer
        chart_ref: portainer/portainer
        release_namespace: portainer
        create_namespace: true
        wait: true
        timeout: "10m0s"
        kubeconfig: "{{ k8s_config }}"
        values:
          service:
            type: LoadBalancer
            # We attempt to set this here, but the explicit task below guarantees it
            externalTrafficPolicy: Local
          tls:
            force: false
          persistence:
            enabled: true
            storageClass: "rook-ceph-block"
            size: "20Gi"

    # --- NEW TASK: GUARANTEE LOCAL TRAFFIC POLICY ---
    # This automates the manual "kubectl patch" command you ran earlier.
    - name: Force 'Local' Traffic Policy on Portainer Service
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_config }}"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: portainer
            namespace: portainer
          spec:
            externalTrafficPolicy: Local

    - name: Get Portainer Service Info
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: portainer
        namespace: portainer
        kubeconfig: "{{ k8s_config }}"
      register: portainer_svc
      until: portainer_svc.resources[0].status.loadBalancer.ingress is defined
      retries: 10
      delay: 5

    - name: Display Portainer Login URL
      debug:
        msg: 
          - "========================================================"
          - "DEPLOYMENT SUCCESSFUL!"
          - "Go here immediately to set your admin password:"
          - "https://{{ portainer_svc.resources[0].status.loadBalancer.ingress[0].ip }}:9443"
          - "========================================================"
          - "NOTE: You have 5 minutes to set the password."
          - "If you get a 'timeout' error, run: kubectl --kubeconfig /etc/kubernetes/admin.conf rollout restart deploy portainer -n portainer"
