---
- name: 06 - Deploy Kube-VIP and Portainer
  hosts: node1
  become: true
  vars:
    k8s_config: /etc/kubernetes/admin.conf
    kv_version: "v0.8.0"
    vip_range: "10.6.4.150-10.6.4.200"

  tasks:
    - name: Ensure Helm is in the System Path
      file:
        src: /usr/local/bin/helm
        dest: /usr/bin/helm
        state: link
        force: yes
      ignore_errors: yes

    - name: Enable strictARP in kube-proxy
      shell: |
        export KUBECONFIG={{ k8s_config }}
        kubectl get configmap kube-proxy -n kube-system -o yaml | \
        sed -e "s/strictARP: false/strictARP: true/" | \
        kubectl apply -f - -n kube-system
      register: strict_arp_patch
      changed_when: "'configured' in strict_arp_patch.stdout"

    - name: Apply Kube-VIP RBAC Manifest
      kubernetes.core.k8s:
        state: present
        src: https://kube-vip.io/manifests/rbac.yaml
        kubeconfig: "{{ k8s_config }}"

    - name: Create Kube-VIP IP Range ConfigMap
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_config }}"
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: kubevip
            namespace: kube-system
          data:
            range-global: "{{ vip_range }}"

    - name: Apply Kube-VIP Cloud Provider
      kubernetes.core.k8s:
        state: present
        src: "https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml"
        kubeconfig: "{{ k8s_config }}"

    - name: Deploy Kube-VIP DaemonSet
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_config }}"
        definition:
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: kube-vip-ds
            namespace: kube-system
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: kube-vip-ds
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: kube-vip-ds
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: node-role.kubernetes.io/master
                          operator: Exists
                      - matchExpressions:
                        - key: node-role.kubernetes.io/control-plane
                          operator: Exists
                hostNetwork: true
                serviceAccountName: kube-vip
                tolerations:
                - effect: NoSchedule
                  operator: Exists
                - effect: NoExecute
                  operator: Exists
                containers:
                - name: kube-vip
                  image: ghcr.io/kube-vip/kube-vip:{{ kv_version }}
                  imagePullPolicy: IfNotPresent
                  args:
                  - manager
                  env:
                  - name: vip_arp
                    value: "true"
                  - name: svc_enable
                    value: "true"

                  - name: vip_interface
                    value: "" 
                    
                  - name: vip_cidr
                    value: "32"
                  - name: cp_enable
                    value: "false"
                  - name: cp_namespace
                    value: kube-system
                  securityContext:
                    capabilities:
                      add:
                      - NET_ADMIN
                      - NET_RAW

    - name: Add Portainer Helm repository
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: https://portainer.github.io/k8s/

    - name: Install Portainer using Helm
      kubernetes.core.helm:
        name: portainer
        chart_ref: portainer/portainer
        release_namespace: portainer
        create_namespace: true
        wait: true
        timeout: "10m0s"
        kubeconfig: "{{ k8s_config }}"
        values:
          service:
            type: LoadBalancer
            externalTrafficPolicy: Cluster
            httpPort: 9000
            httpsPort: 9443
          tls:
            force: false
          persistence:
            enabled: true
            storageClass: "rook-ceph-block"
            size: "20Gi"

    - name: Get Portainer Service Info
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: portainer
        namespace: portainer
        kubeconfig: "{{ k8s_config }}"
      register: portainer_svc
      until: portainer_svc.resources[0].status.loadBalancer.ingress is defined
      retries: 20
      delay: 10

    - name: Display Portainer Login URL
      debug:
        msg: 
          - "========================================================"
          - "KUBE-VIP & PORTAINER DEPLOYMENT SUCCESSFUL!"
          - "Go here immediately to set your admin password:"
          - "https://{{ portainer_svc.resources[0].status.loadBalancer.ingress[0].ip }}:9443"
          - "========================================================"
