---
- name: 06 - Deploy Portainer using Helm
  hosts: node1
  become: no
  gather_facts: no
  vars:
    portainer_namespace: portainer
    storage_class_name: rook-ceph-block # Must match the StorageClass created by Rook

  tasks:
    - name: Add Helm repository for Portainer
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: https://portainer.github.io/k8s/
        state: present

    - name: Update Helm repositories
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: https://portainer.github.io/k8s/
        state: update

    - name: Install Portainer using Helm
      kubernetes.core.helm:
        name: portainer
        chart_ref: portainer/portainer
        release_namespace: "{{ portainer_namespace }}"
        create_namespace: yes
        state: present
        values:
          service:
            type: NodePort # Exposes Portainer on a high port (30000-32767) on all nodes
          tls:
            force: true
          persistence:
            enabled: true
            storageClass: "{{ storage_class_name }}"
            size: 10Gi

    - name: Get Portainer NodePort for access info
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: portainer
        namespace: portainer
      register: portainer_service

    - name: Display Portainer Access URL
      ansible.builtin.debug:
        msg: "Portainer is accessible via HTTPS on node1 ({{ hostvars['node1']['ansible_host'] }}) on NodePort: {{ portainer_service.resources[0].spec.ports[0].nodePort }}. URL: https://{{ hostvars['node1']['ansible_host'] }}:{{ portainer_service.resources[0].spec.ports[0].nodePort }}"
